language: python
 
before_script:
  - pip install -r requirements.txt

script:
  - python --version
  - python restapitest3.py

notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
