image: ubuntu

test_script:
- ls -ltrh
- sudo apt-get update
- sudo apt-get install python3-pip -y
- pip3 install -r requirements.txt
- python3 restapitest3.py
- python3 restapitest2.py
- python3 findtag.py
- python3 findrresult.py
- cat std.log

build: off
