image: ubuntu

test_script:
- ls -ltrh
- sudo apt-get update
- sudo apt-get install python3-pip -y
- pip3 install -r requirements.txt
- python3 restapitest.py
- python restapitest2.py
- python findtag.py
- python findrresult.py

build: off
