version: '2.1'
orbs:
  python: circleci/python@2.0.3
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            python --version
            python restapitest3.py
            python restapitest2.py
            python findtag.py
            python findrresult.py
            cat std.log
            mkdir -p /tmp/artifacts
            cp std.log /tmp/artifacts/std.log
          name: execute python code

      - run:
          name: Print python version
          command: python -V

      - run:
          name: Download python dependencies
          command: pip3 install -t dep -r requirements.txt

      - run:
          name: package the artifacts
          command: cd dep; zip ../lambda_artifact.zip -rv .

      - run:
          name: list directory
          command: ls -ltr

      - run:
          name: package main program
          command: zip lambda_artifact.zip -u main.py

      - run:
          name: list directory
          command: ls -ltr

      - run:
          name: present workdirectory
          command: pwd

      - run:
          name: take artifacts snapshot
          command: cp -v lambda_artifact.zip /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  main:
    jobs:
      - build
